# Generated by Django 5.0.6 on 2024-05-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='app_secret_token',
            field=models.CharField(default='15c3cdd751374aaa83efb51fffd69e94', editable=False, max_length=255),
        ),
    ]
